export default {
    CC_Number: '[name="cc-number"]',
    CC_Name: '[name="cc-name"]',
    CC_Exp: '[name="cc-exp"]',
    CC_CSC: '[name="cc-csc"]',

    Country: '//span[contains(@class, \'mat-select-placeholder mat-select-min-line\')]',
    PANEL_CountrySelection: '(//mat-option[@role=\'option\'])[1]',
                                
    City: '//input[@formcontrolname=\'city\']',
    ZIPCode: '//input[@formcontrolname=\'zipCode\']',
    Address: '//input[@formcontrolname=\'address\']',
    Contact: '//input[@formcontrolname=\'email\']',

    Accept_information: '(//label[@class=\'mat-checkbox-layout\']//span)[1]',
    BTN_Continueandpay: '//div[@class=\'payment-button\']//button[1]',

    BTN_Debug:'(//input[@type=\'submit\'])[3]',
    TXT_Bank_Process_Date: '//input[@id=\'txtBankProcessDate\']',
    TXT_Authorization_ID: '//input[@id=\'txtAuthorizationID\']',
    BTN_Call: '(//input[@type=\'submit\'])[1]',
    BTN_Return: '(//input[@type=\'submit\'])[2]',

    RDB_DebitOption: '//div[@class=\'radio-button ng-star-inserted\']',
    SLC_SelectBank: '(//div[@class=\'mat-select-value\']//span)[1]',
    SLC_BUC: '//span[text()=\' Banco Union Colombiano \']',
    RDB_NaturalPerson: '(//span[@class=\'mat-radio-label-content\'])[1]',
    SLC_DocumentID: '(//div[@class=\'mat-select-arrow\'])[2]',
    SLC_CC_Selection: '(//span[@class=\'mat-option-text\'])[1]',
    TXT_CC_Number_DD: '//div[@class=\'mat-form-field-infix\']//input[1]',
    CHCK_PrivacyPolicy: '(//label[@class=\'mat-checkbox-layout\']//span)[1]',
    BTN_SecurePayment: '//div[@class=\'button-section\']//button[1]',
    SLC_PlaceOfIssueOfTheCard:'(//div[contains(@class,\'abc-form-element-main abc-form-element-select\')])[2]',
    SLC_PlaceOfIssueOfTheCardOption:'//div[contains(@class,\'abc-form-element-option abc-options-panel-spacer\')]/following-sibling::li[1]',
    RDB_OnsiteOption: '(//div[@class=\'radio-button ng-star-inserted\']/following-sibling::h2)[2]',
    RDB_BancoBogota: '(//span[@class=\'mat-radio-container\']/following-sibling::span)[1]',

    
    TXT_cardHolderName:'//input[@formcontrolname=\'firstName\']',
    TXT_cardHolderSurname:'//input[@formcontrolname=\'lastName\']',
    TXT_cardHolderEmail:'//input[@formcontrolname=\'email\']',
    TXT_cardHolderIdNumber:'//input[@formcontrolname=\'dniNumber\']',
    TXT_cardHolderPhoneNumber:'(//input[@formcontrolname=\'number\'])[2]',
    SLC_DocumentType:'(//div[@role=\'option\'])[3]',
    SLC_DocumentTypeSelect:'//ul[@class=\'abc-form-element-options-list no-highlight\']//li[1]',
    SLC_AreaCode:'//div[@id=\'abcElement1\']/div[1]/div[1]',
    SLC_AreaCodeSelect:'//ul[@class=\'abc-form-element-options-list no-highlight\']//li[1]',

    TXT_cardNumber:'[name="cardNumber"]',
    TXT_cardExpiryDate:'[name="expiryDate"]',
    TXT_cardVerificationCode:'[name="cvv"]',
    TXT_cardHolderNameCPD:'[name="firstname"]',
    TXT_cardHolderSurnameCPD:'[name="surname"]',
    SLC_DocumentTypeCPD:'(//div[contains(@class,\'MuiSelect-root MuiSelect-select\')])[2]',
    SLC_DocumentTypeSelectCPD:'//li[@data-value=\'1\']',
    TXT_cardHolderIdNumberCPD:'[name="iDNumber"]',
    TXT_cardHolderEmailCPD:'[name="email"]',
    SLC_AreaCodeCPD:'(//div[contains(@class,\'MuiSelect-root MuiSelect-select\')])[3]',
    SLC_AreaCodeSelectCPD:'//li[@data-value=\'55\']',
    TXT_cardHolderPhoneNumberCPD:'[name="phoneNumber"]',
    CHCK_InternationalPrivacyPolicyCPD:'(//input[@id=\'tnc_checkBox\'])[2]',
    BTN_continueAndPayCPD:'(//span[@class=\'MuiButton-label\'])[1]',
    TXT_cityCPD:'[name="city"]',
    TXT_addressCPD:'[name="address"]',
    SLC_State:'//div[@id=\'abcElement4SelectedOption\']',
    SLC_StateSelect: '(//li[contains(@class,\'abc-form-element-option no-highlight\')])[1]',
    CHCK_InternationalPrivacyPolicy: '(//span[@class=\'mat-checkbox-inner-container\'])[2]',

    

}
